import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { ArrowLeft } from '@phosphor-icons/react'

interface LegalPagesProps {
  currentPage: 'terms' | 'privacy' | 'cookies'
  onBack: () => void
}

export function LegalPages({ currentPage, onBack }: LegalPagesProps) {
  const renderTermsAndConditions = () => (
    <div className="space-y-4 text-xs leading-relaxed">
      <h1 className="text-2xl font-bold text-foreground mb-6">Terms and Conditions</h1>
      
      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">1. Acceptance of Terms</h2>
        <p className="text-muted-foreground">
          These Terms and Conditions ("Terms", "Terms and Conditions") govern your relationship with Miky.ai website and application 
          (the "Service") operated by Neuronica Srl ("us", "we", or "our"). By accessing and using our Service, you accept and agree 
          to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
        </p>
        <p className="text-muted-foreground">
          These Terms apply to all visitors, users and others who access or use the Service. Your access to and use of the Service is 
          conditioned on your acceptance of and compliance with these Terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">2. Service Description</h2>
        <p className="text-muted-foreground">
          Miky.ai is an artificial intelligence assistant platform that provides specialized AI personas designed for various professional 
          and personal assistance needs. Our Service offers multiple AI personas including but not limited to: Lawyer, Engineer, Marketer, 
          Coach, Medical Advisor, and God Mode for advanced queries.
        </p>
        <p className="text-muted-foreground">
          The Service operates on a credit-based system with multiple subscription tiers (Free, Plus, Business) and allows users to purchase 
          additional credits. All AI responses are generated by artificial intelligence and should be used for informational purposes only.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">3. User Accounts and Registration</h2>
        <p className="text-muted-foreground">
          You must be at least 13 years of age to use this Service. If you are under 18, you must have your parent or legal guardian's 
          permission to use the Service. By creating an account, you represent and warrant that you meet these age requirements.
        </p>
        <p className="text-muted-foreground">
          When you create an account with us, you must provide information that is accurate, complete, and current at all times. You are 
          responsible for safeguarding the password and for all activities that occur under your account. You must notify us immediately 
          upon becoming aware of any breach of security or unauthorized use of your account.
        </p>
        <p className="text-muted-foreground">
          We reserve the right to refuse service, terminate accounts, remove or edit content in our sole discretion.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">4. Credit System and Payments</h2>
        <p className="text-muted-foreground">
          Our Service operates on a credit-based system where credits are consumed when interacting with AI personas. Different personas 
          and actions may consume different amounts of credits. Credit consumption rates are not disclosed to users but are consistently 
          applied across the platform.
        </p>
        <p className="text-muted-foreground">
          Subscription plans include: (a) Free Plan: 100 credits per month with limited features; (b) Plus Plan: $19/month for 1,000 credits 
          and enhanced features; (c) Business Plan: $49/month for 5,000 credits and premium features. Additional credits may be purchased separately.
        </p>
        <p className="text-muted-foreground">
          All payments are processed through Stripe. Subscription fees are charged in advance on a monthly basis and are non-refundable except 
          as required by applicable law. We reserve the right to change our pricing with 30 days notice to existing subscribers.
        </p>
        <p className="text-muted-foreground">
          Credits do not expire and remain in your account until used. In case of account termination, unused credits are forfeited without compensation.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">5. Prohibited Uses</h2>
        <p className="text-muted-foreground">
          You may not use our Service: (a) for any unlawful purpose or to solicit others to perform unlawful acts; (b) to violate any international, 
          federal, provincial or state regulations, rules, laws, or local ordinances; (c) to infringe upon or violate our intellectual property 
          rights or the intellectual property rights of others; (d) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, 
          or discriminate; (e) to submit false or misleading information; (f) to upload or transmit viruses or any other type of malicious code.
        </p>
        <p className="text-muted-foreground">
          Additionally, you agree not to: (a) use the Service to generate content that is illegal, harmful, threatening, abusive, defamatory, 
          or otherwise objectionable; (b) attempt to circumvent or manipulate the credit system; (c) reverse engineer, decompile, or attempt 
          to extract the source code of the Service; (d) use automated systems to access the Service without explicit permission.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">6. Intellectual Property Rights</h2>
        <p className="text-muted-foreground">
          The Service and its original content, features and functionality are and will remain the exclusive property of Neuronica Srl and its 
          licensors. The Service is protected by copyright, trademark, and other laws of the Republic of San Marino and foreign countries. 
          Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent.
        </p>
        <p className="text-muted-foreground">
          You retain ownership of content you provide to the Service, but grant us a worldwide, non-exclusive, royalty-free license to use, 
          modify, and display such content for the purpose of providing the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">7. AI-Generated Content Disclaimer</h2>
        <p className="text-muted-foreground">
          All responses provided by our AI personas are generated by artificial intelligence and are provided for informational purposes only. 
          The AI-generated content should not be considered as professional advice in any field including but not limited to legal, medical, 
          financial, or technical advice.
        </p>
        <p className="text-muted-foreground">
          We do not guarantee the accuracy, completeness, or reliability of AI-generated responses. Users should verify information independently 
          and consult with appropriate professionals before making decisions based on AI-generated content.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">8. Limitation of Liability</h2>
        <p className="text-muted-foreground">
          In no event shall Neuronica Srl, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, 
          incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other 
          intangible losses, resulting from your use of the Service.
        </p>
        <p className="text-muted-foreground">
          Our total liability to you for any damages arising from or related to this agreement or your use of the Service shall not exceed 
          the amount you have paid us in the twelve (12) months immediately preceding the event giving rise to the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">9. Termination</h2>
        <p className="text-muted-foreground">
          We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our 
          sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
        </p>
        <p className="text-muted-foreground">
          If you wish to terminate your account, you may simply discontinue using the Service. Upon termination, your right to use the 
          Service will cease immediately and any unused credits will be forfeited.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">10. Referral Program</h2>
        <p className="text-muted-foreground">
          Our referral program allows users to earn bonus credits by referring new users to the Service. Both the referrer and referee receive 
          100 bonus credits upon successful signup. Referral abuse, including but not limited to creating fake accounts, will result in 
          immediate account termination.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">11. Governing Law and Jurisdiction</h2>
        <p className="text-muted-foreground">
          These Terms shall be interpreted and governed by the laws of the Republic of San Marino, without regard to its conflict of law 
          provisions. Any disputes arising from these Terms or your use of the Service shall be subject to the exclusive jurisdiction of 
          the courts of the Republic of San Marino.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">12. Changes to Terms</h2>
        <p className="text-muted-foreground">
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will 
          provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at 
          our sole discretion.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">13. Contact Information</h2>
        <p className="text-muted-foreground">
          If you have any questions about these Terms and Conditions, please contact us at:
        </p>
        <p className="text-muted-foreground">
          Email: support@miky.ai<br />
          Neuronica Srl<br />
          Via del Serrone 62<br />
          47890 Repubblica di San Marino
        </p>
      </section>

      <p className="text-xs text-muted-foreground mt-8 pt-4 border-t border-border">
        Last updated: August 2, 2025
      </p>
    </div>
  )

  const renderPrivacyPolicy = () => (
    <div className="space-y-4 text-xs leading-relaxed">
      <h1 className="text-2xl font-bold text-foreground mb-6">Privacy Policy</h1>
      
      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">1. Introduction</h2>
        <p className="text-muted-foreground">
          Neuronica Srl ("we", "our", or "us") operates the Miky.ai website and application (the "Service"). This Privacy Policy informs 
          you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you 
          have associated with that data.
        </p>
        <p className="text-muted-foreground">
          We are committed to protecting your privacy and ensuring the security of your personal information. This policy complies with 
          applicable data protection laws including the General Data Protection Regulation (GDPR).
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">2. Information We Collect</h2>
        <h3 className="text-sm font-medium text-foreground">2.1 Personal Information</h3>
        <p className="text-muted-foreground">
          We collect information you provide directly to us, including: (a) Account information (email address, username, password); 
          (b) Profile information (preferences, language settings); (c) Payment information (processed by Stripe, we do not store 
          full payment details); (d) Communication data (support requests, feedback).
        </p>
        
        <h3 className="text-sm font-medium text-foreground">2.2 Usage Information</h3>
        <p className="text-muted-foreground">
          We automatically collect information about your use of the Service, including: (a) Conversation history with AI personas; 
          (b) Credit usage patterns and transaction history; (c) Feature usage and interaction data; (d) Technical information 
          (IP address, browser type, device information); (e) Analytics data (session duration, page views, user flows).
        </p>

        <h3 className="text-sm font-medium text-foreground">2.3 Voice Data</h3>
        <p className="text-muted-foreground">
          When you use voice input features, we process audio data to convert speech to text. Voice recordings are processed locally 
          in your browser when possible and are not permanently stored on our servers.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">3. How We Use Your Information</h2>
        <p className="text-muted-foreground">
          We use the collected information for the following purposes: (a) To provide, maintain, and improve our Service; (b) To process 
          transactions and manage your account; (c) To personalize your experience and provide relevant AI responses; (d) To communicate 
          with you about our Service, including updates and support; (e) To detect, prevent, and address technical issues and security threats; 
          (f) To comply with legal obligations and protect our rights.
        </p>
        <p className="text-muted-foreground">
          We process your personal data based on the following legal grounds: (a) Performance of contract (providing the Service); 
          (b) Legitimate interests (improving our Service, security); (c) Consent (marketing communications); (d) Legal compliance.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">4. Information Sharing and Disclosure</h2>
        <p className="text-muted-foreground">
          We do not sell, trade, or otherwise transfer your personal information to third parties except as described in this policy. 
          We may share your information with: (a) Service providers (Stripe for payments, hosting providers, analytics services) who 
          assist us in operating our Service; (b) Legal authorities when required by law or to protect our rights; (c) Business partners 
          in case of merger, acquisition, or sale of assets (with prior notice).
        </p>
        <p className="text-muted-foreground">
          All third-party service providers are contractually obligated to protect your information and use it only for the specific 
          purposes we authorize.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">5. Data Security</h2>
        <p className="text-muted-foreground">
          We implement appropriate technical and organizational security measures to protect your personal information against unauthorized 
          access, alteration, disclosure, or destruction. These measures include: (a) Encryption of data in transit and at rest; 
          (b) Regular security assessments and updates; (c) Access controls and authentication mechanisms; (d) Secure payment processing 
          through PCI-compliant providers.
        </p>
        <p className="text-muted-foreground">
          However, no method of transmission over the Internet or method of electronic storage is 100% secure. We cannot guarantee 
          absolute security of your information.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">6. Data Retention</h2>
        <p className="text-muted-foreground">
          We retain your personal information for as long as necessary to provide the Service and fulfill the purposes outlined in this 
          policy. Specific retention periods include: (a) Account information: Until account deletion or 3 years of inactivity; 
          (b) Conversation history: Until manually deleted by user or account termination; (c) Payment information: As required by 
          financial regulations (typically 7 years); (d) Analytics data: Aggregated and anonymized after 2 years.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">7. Your Rights</h2>
        <p className="text-muted-foreground">
          Under applicable data protection laws, you have the following rights: (a) Access: Request copies of your personal data; 
          (b) Rectification: Request correction of inaccurate or incomplete data; (c) Erasure: Request deletion of your personal data; 
          (d) Restriction: Request limitation of processing in certain circumstances; (e) Portability: Request transfer of your data 
          to another service; (f) Objection: Object to processing based on legitimate interests.
        </p>
        <p className="text-muted-foreground">
          To exercise these rights, contact us at support@miky.ai. We will respond to your request within 30 days. Some rights may be 
          limited by legal requirements or the nature of our Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">8. International Transfers</h2>
        <p className="text-muted-foreground">
          Your information may be transferred to and processed in countries other than your country of residence, including the Republic 
          of San Marino where our company is located. We ensure that such transfers comply with applicable data protection laws through 
          appropriate safeguards such as standard contractual clauses.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">9. Children's Privacy</h2>
        <p className="text-muted-foreground">
          Our Service is not intended for children under 13 years of age. We do not knowingly collect personal information from children 
          under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us 
          to have the information removed.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">10. Changes to This Privacy Policy</h2>
        <p className="text-muted-foreground">
          We may update our Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy 
          on this page and updating the "Last updated" date. For significant changes, we may also send you an email notification.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">11. Contact Information</h2>
        <p className="text-muted-foreground">
          If you have any questions about this Privacy Policy or our data practices, please contact us at:
        </p>
        <p className="text-muted-foreground">
          Email: support@miky.ai<br />
          Data Protection Officer: Neuronica Srl<br />
          Via del Serrone 62<br />
          47890 Repubblica di San Marino
        </p>
      </section>

      <p className="text-xs text-muted-foreground mt-8 pt-4 border-t border-border">
        Last updated: August 2, 2025
      </p>
    </div>
  )

  const renderCookiePolicy = () => (
    <div className="space-y-4 text-xs leading-relaxed">
      <h1 className="text-2xl font-bold text-foreground mb-6">Cookie Policy</h1>
      
      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">1. What Are Cookies</h2>
        <p className="text-muted-foreground">
          Cookies are small text files that are placed on your computer, smartphone, or other device when you visit our website. 
          They are widely used to make websites work more efficiently and to provide information to website owners. Cookies contain 
          information that is transferred to your device's hard drive.
        </p>
        <p className="text-muted-foreground">
          We use cookies to enhance your experience on our website, remember your preferences, and analyze how our Service is used. 
          This Cookie Policy explains what cookies are, how we use them, the types of cookies we use, and how you can control them.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">2. Types of Cookies We Use</h2>
        
        <h3 className="text-sm font-medium text-foreground">2.1 Essential Cookies</h3>
        <p className="text-muted-foreground">
          These cookies are strictly necessary for the operation of our Service. They enable you to navigate around the website and 
          use its features. Without these cookies, services you have asked for cannot be provided. These cookies include: 
          (a) Authentication cookies that identify you when you log in; (b) Security cookies that help detect malicious activity; 
          (c) Load balancing cookies that ensure the website runs smoothly.
        </p>

        <h3 className="text-sm font-medium text-foreground">2.2 Functionality Cookies</h3>
        <p className="text-muted-foreground">
          These cookies remember choices you make and provide enhanced, more personal features. They may be set by us or by third-party 
          providers whose services we have added to our pages. These include: (a) Language preference cookies; (b) Theme and display 
          preference cookies; (c) User interface customization cookies; (d) Recently used personas and conversation history.
        </p>

        <h3 className="text-sm font-medium text-foreground">2.3 Analytics and Performance Cookies</h3>
        <p className="text-muted-foreground">
          These cookies collect information about how visitors use our website, such as which pages are visited most often and if 
          visitors get error messages from web pages. The information collected is aggregated and anonymous. We use this information 
          to improve how our website works. These cookies help us: (a) Understand user behavior and preferences; (b) Identify and 
          fix technical issues; (c) Optimize website performance and user experience.
        </p>

        <h3 className="text-sm font-medium text-foreground">2.4 Advertising and Marketing Cookies</h3>
        <p className="text-muted-foreground">
          These cookies are used to deliver advertisements that are relevant to you and your interests. They may also be used to 
          limit the number of times you see an advertisement and help measure the effectiveness of advertising campaigns. Currently, 
          we do not use advertising cookies, but this may change in the future with appropriate notice.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">3. Third-Party Cookies</h2>
        <p className="text-muted-foreground">
          In addition to our own cookies, we may also use various third-party cookies to report usage statistics of the Service and 
          deliver advertisements. These third-party services include:
        </p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
          <li><strong>Stripe:</strong> For secure payment processing and fraud prevention</li>
          <li><strong>Analytics Services:</strong> To understand how users interact with our Service</li>
          <li><strong>Performance Monitoring:</strong> To ensure optimal website performance</li>
        </ul>
        <p className="text-muted-foreground">
          These third parties may collect information about your online activities over time and across different websites when you 
          use our Service. We do not control these third-party cookies and recommend reviewing their respective privacy policies.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">4. How Long Do Cookies Last</h2>
        <p className="text-muted-foreground">
          Cookies may be either "session cookies" or "persistent cookies". Session cookies are temporary and are deleted when you 
          close your browser. Persistent cookies remain on your device for a set period or until you delete them manually.
        </p>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
          <li><strong>Session cookies:</strong> Authentication, security, and temporary preferences</li>
          <li><strong>Persistent cookies (30 days):</strong> Language preferences, theme settings</li>
          <li><strong>Persistent cookies (1 year):</strong> Analytics data, performance optimization</li>
          <li><strong>Persistent cookies (2 years):</strong> User experience improvements</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">5. Managing and Controlling Cookies</h2>
        <h3 className="text-sm font-medium text-foreground">5.1 Browser Settings</h3>
        <p className="text-muted-foreground">
          Most web browsers allow you to control cookies through their settings preferences. You can set your browser to refuse cookies 
          or to alert you when cookies are being sent. However, please note that if you disable or refuse cookies, some parts of our 
          Service may become inaccessible or not function properly.
        </p>

        <h3 className="text-sm font-medium text-foreground">5.2 Browser-Specific Instructions</h3>
        <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4">
          <li><strong>Chrome:</strong> Settings → Privacy and Security → Cookies and other site data</li>
          <li><strong>Firefox:</strong> Preferences → Privacy & Security → Cookies and Site Data</li>
          <li><strong>Safari:</strong> Preferences → Privacy → Manage Website Data</li>
          <li><strong>Edge:</strong> Settings → Site permissions → Cookies and site data</li>
        </ul>

        <h3 className="text-sm font-medium text-foreground">5.3 Mobile Devices</h3>
        <p className="text-muted-foreground">
          For mobile devices, you can manage cookies through your device's browser settings or through the privacy settings in our 
          mobile application if applicable.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">6. Cookie Consent</h2>
        <p className="text-muted-foreground">
          When you first visit our website, we may display a cookie banner asking for your consent to use non-essential cookies. 
          You can withdraw your consent at any time by changing your browser settings or contacting us. Essential cookies will 
          continue to be used as they are necessary for the basic functionality of our Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">7. Updates to This Cookie Policy</h2>
        <p className="text-muted-foreground">
          We may update this Cookie Policy from time to time to reflect changes in our practices or for other operational, legal, 
          or regulatory reasons. We will notify you of any material changes by posting the new Cookie Policy on this page and 
          updating the "Last updated" date.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">8. Legal Basis for Cookie Use</h2>
        <p className="text-muted-foreground">
          Our use of cookies is based on the following legal grounds: (a) Essential cookies: Necessary for the performance of our 
          contract with you; (b) Functionality cookies: Based on your consent and our legitimate interest in providing a better user 
          experience; (c) Analytics cookies: Based on our legitimate interest in improving our Service; (d) Marketing cookies: 
          Based on your explicit consent (if implemented in the future).
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-foreground">9. Contact Information</h2>
        <p className="text-muted-foreground">
          If you have any questions about our use of cookies or this Cookie Policy, please contact us at:
        </p>
        <p className="text-muted-foreground">
          Email: support@miky.ai<br />
          Neuronica Srl<br />
          Via del Serrone 62<br />
          47890 Repubblica di San Marino
        </p>
      </section>

      <p className="text-xs text-muted-foreground mt-8 pt-4 border-t border-border">
        Last updated: August 2, 2025
      </p>
    </div>
  )

  const getContent = () => {
    switch (currentPage) {
      case 'terms':
        return renderTermsAndConditions()
      case 'privacy':
        return renderPrivacyPolicy()
      case 'cookies':
        return renderCookiePolicy()
      default:
        return null
    }
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-5xl">
        <Button
          variant="ghost"
          onClick={onBack}
          className="mb-6 p-2"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to App
        </Button>
        
        <Card className="p-8">
          {getContent()}
        </Card>
      </div>
    </div>
  )
}